DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ai_agent') THEN
    CREATE ROLE ai_agent LOGIN PASSWORD 'ai_agent_dev';
  END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE ai_agent TO ai_agent;
GRANT ALL ON SCHEMA public TO ai_agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ai_agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ai_agent;
